/**
 * Catálogo de ejemplo — reemplazá precios e imágenes con tu inventario real.
 * Estructura alineada a referencias del rubro (p. ej. productos destacados tipo tuiphone.cl).
 */
window.PRODUCTS_DATA = [
  {
    id: "mb-a1278",
    title: 'MacBook Pro A1278 13" i5 4GB RAM',
    category: "mac",
    categoryLabel: "Mac",
    condition: "seminuevo",
    price: 199990,
    oldPrice: 449990,
    image:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=800&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&h=800&fit=crop&q=80",
    ],
    colors: [
      { name: "Gris Espacial", hex: "#4a4a4a" },
      { name: "Plata", hex: "#c0c0c0" },
    ],
    capacities: ["4 GB RAM", "8 GB RAM"],
    description: "Equipo revisado, ideal para estudio y oficina.",
    longDescription:
      'El MacBook Pro A1278 de 13 pulgadas con procesador Intel Core i5 es una opción ideal para quienes buscan un equipo confiable para tareas de oficina, estudio y navegación. Su pantalla de 13.3 pulgadas ofrece una resolución nítida y colores fieles, mientras que su teclado retroiluminado facilita el trabajo en cualquier ambiente.\n\nEste equipo ha sido completamente revisado y testeado por nuestro equipo técnico, asegurando un funcionamiento óptimo. La batería ha sido evaluada y mantiene una autonomía adecuada para uso diario.',
    specs: {
      Pantalla: '13.3" LED-backlit',
      Procesador: "Intel Core i5 2.5 GHz",
      "Memoria RAM": "4 GB DDR3",
      Almacenamiento: "500 GB HDD",
      "Sistema operativo": "macOS Catalina",
      Batería: "Hasta 7 hrs de uso",
      Puertos: "USB 3.0, Thunderbolt, SD, HDMI",
      Peso: "2.06 kg",
    },
    reviews: [
      {
        author: "Carlos M.",
        rating: 5,
        date: "hace 3 meses",
        text: "Excelente equipo para trabajar. Llegó en perfectas condiciones, muy bien cuidado. Recomendado.",
      },
      {
        author: "Laura P.",
        rating: 4,
        date: "hace 6 meses",
        text: "Buen rendimiento para tareas básicas. La batería dura lo esperado. Muy contenta con la compra.",
      },
    ],
    chargerPrice: 14990,
  },
  {
    id: "iphone-xr",
    title: "iPhone XR",
    category: "iphone",
    categoryLabel: "iPhone",
    condition: "seminuevo",
    price: 189990,
    oldPrice: 349990,
    image:
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&h=800&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1591337676887-a217a6c8c589?w=800&h=800&fit=crop&q=80",
    ],
    colors: [
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Azul", hex: "#1a3f7a" },
      { name: "Rojo", hex: "#c0392b" },
      { name: "Amarillo", hex: "#f1c40f" },
      { name: "Coral", hex: "#e74c3c" },
    ],
    capacities: ["64 GB", "128 GB", "256 GB"],
    description: "Pantalla Liquid Retina, gran batería.",
    longDescription:
      "El iPhone XR fue lanzado por Apple, como una opción más asequible en comparación con otros modelos de iPhone lanzados al mismo tiempo. Este teléfono inteligente cuenta con una pantalla táctil Liquid Retina de 6,1 pulgadas con tecnología IPS, que ofrece una resolución de 1792 x 828 píxeles y una densidad de píxeles de 326 ppp. Su diseño de vidrio en la parte frontal y trasera, con un marco de aluminio de alta calidad, lo hace atractivo y moderno.\n\nEl iPhone XR está equipado con el procesador A12 Bionic de seis núcleos, lo que garantiza un rendimiento rápido y fluido en todas las aplicaciones. También cuenta con una cámara trasera de 12 megapíxeles con estabilización óptica de imagen, que permite tomar fotos y videos de calidad excepcional, incluso en condiciones de poca luz. Además, su cámara frontal TrueDepth de 7 megapíxeles es ideal para videollamadas y selfies, y cuenta con la función de Retina Flash para obtener selfies más naturales en condiciones de poca luz.\n\nEn general, el iPhone XR es una excelente opción para aquellos usuarios que buscan un teléfono inteligente con un diseño atractivo y características técnicas avanzadas a un precio más accesible que otros modelos de iPhone.",
    specs: {
      Pantalla: '6.1" Liquid Retina IPS',
      Resolución: "1792 x 828 px (326 ppi)",
      Procesador: "A12 Bionic",
      "Cámara trasera": "12 MP con OIS",
      "Cámara frontal": "7 MP TrueDepth",
      "Resistencia al agua": "IP67",
      "Face ID": "Sí",
      Batería: "Hasta 16 hrs reproducción de video",
      Peso: "194 g",
    },
    reviews: [
      {
        author: "Gonzalo E.",
        rating: 5,
        date: "hace 9 meses",
        text: "Todo bien con el iPhone, llegó en super buen estado y funciona como nuevo. Recomendado.",
      },
      {
        author: "Josefina C.",
        rating: 5,
        date: "hace 2 años",
        text: "Compramos el iPhone XR junto a un iPad y salió todo de maravilla, la atención del joven de la oficina muy buena. Nicolás creo que se llamaba. Muchas gracias.",
      },
      {
        author: "Miguel A.",
        rating: 5,
        date: "hace 2 años",
        text: "Como usuario del iPhone XR de 64GB, puedo decir que estoy muy impresionado con su rendimiento y características. La pantalla Liquid Retina es vibrante y nítida, ideal para ver contenido multimedia y navegar por la web. La cámara de 12 megapíxeles captura fotos y videos de alta calidad, incluso en condiciones de poca luz. Me encanta. Buen teléfono a un precio accesible.",
      },
    ],
    chargerPrice: 9990,
  },
  {
    id: "ps4-500",
    title: "PlayStation 4 — 500GB con control",
    category: "otros",
    categoryLabel: "Videojuegos",
    condition: "seminuevo",
    price: 179990,
    oldPrice: 399990,
    image:
      "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=800&h=800&fit=crop&q=80",
    ],
    colors: [
      { name: "Negro", hex: "#1a1a1a" },
      { name: "Blanco", hex: "#f5f5f5" },
    ],
    capacities: ["500 GB", "1 TB"],
    description: "Consola + un control DualShock.",
    longDescription:
      "La PlayStation 4 es una consola de videojuegos de última generación que ofrece una experiencia de juego increíble. Con un disco duro de 500GB, tendrás espacio más que suficiente para tus juegos favoritos. Incluye un control DualShock 4 inalámbrico con todas sus funcionalidades.\n\nEste equipo ha sido completamente revisado y testeado, asegurando un funcionamiento óptimo en todos los juegos y aplicaciones multimedia.",
    specs: {
      Procesador: "AMD Jaguar x86-64 8 núcleos",
      GPU: "AMD Radeon 1.84 TFLOPS",
      RAM: "8 GB GDDR5",
      Almacenamiento: "500 GB HDD",
      "Salida de video": "HDMI (hasta 1080p)",
      Conectividad: "Wi-Fi, Bluetooth 2.1, USB 3.0",
      "Control incluido": "DualShock 4 inalámbrico",
      Peso: "2.1 kg",
    },
    reviews: [
      {
        author: "Roberto S.",
        rating: 5,
        date: "hace 4 meses",
        text: "La consola funciona perfecta, como nueva. El envío fue rápido y bien embalado.",
      },
      {
        author: "Andrea V.",
        rating: 4,
        date: "hace 1 año",
        text: "Buena compra, el control estaba impecable. Solo le faltaba un poco más de espacio en disco.",
      },
    ],
    chargerPrice: null,
  },
  {
    id: "iphone-x",
    title: "iPhone X",
    category: "iphone",
    categoryLabel: "iPhone",
    condition: "seminuevo",
    price: 189990,
    oldPrice: 379990,
    image:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=800&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=800&h=800&fit=crop&q=80",
    ],
    colors: [
      { name: "Gris Espacial", hex: "#4a4a4a" },
      { name: "Plata", hex: "#c0c0c0" },
    ],
    capacities: ["64 GB", "256 GB"],
    description: "Face ID, OLED Super Retina.",
    longDescription:
      "El iPhone X marcó un hito en la historia de Apple al ser el primer iPhone con pantalla OLED Super Retina de borde a borde y Face ID. Con su diseño completamente de vidrio y acero inoxidable, este dispositivo es elegante y resistente.\n\nSu pantalla Super Retina de 5.8 pulgadas ofrece colores vibrantes y negros profundos gracias a la tecnología OLED. El procesador A11 Bionic proporciona un rendimiento excepcional, y su sistema de cámara dual de 12 MP captura fotos y videos impresionantes.",
    specs: {
      Pantalla: '5.8" OLED Super Retina',
      Resolución: "2436 x 1125 px (458 ppi)",
      Procesador: "A11 Bionic",
      "Cámara trasera": "Dual 12 MP (gran angular + teleobjetivo)",
      "Cámara frontal": "7 MP TrueDepth",
      "Resistencia al agua": "IP67",
      "Face ID": "Sí",
      Batería: "Hasta 13 hrs reproducción de video",
      Peso: "174 g",
    },
    reviews: [
      {
        author: "Pablo R.",
        rating: 5,
        date: "hace 8 meses",
        text: "Excelente teléfono, la pantalla OLED es increíble. Llegó en muy buen estado.",
      },
      {
        author: "María J.",
        rating: 4,
        date: "hace 1 año",
        text: "Buen equipo por el precio. Face ID funciona perfecto. La batería podría ser mejor pero en general muy contenta.",
      },
    ],
    chargerPrice: 9990,
  },
  {
    id: "iphone-13-pm",
    title: "iPhone 13 Pro Max",
    category: "iphone",
    categoryLabel: "iPhone",
    condition: "seminuevo",
    price: 649990,
    oldPrice: 1199990,
    image:
      "https://images.unsplash.com/photo-1632661674596-df8be070a5c5?w=800&h=800&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1632661674596-df8be070a5c5?w=800&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1638038772924-ef79cce2426d?w=800&h=800&fit=crop&q=80",
    ],
    colors: [
      { name: "Grafito", hex: "#4a4a4a" },
      { name: "Oro", hex: "#d4a853" },
      { name: "Plata", hex: "#c0c0c0" },
      { name: "Azul Sierra", hex: "#69abce" },
    ],
    capacities: ["128 GB", "256 GB", "512 GB", "1 TB"],
    description: "Alto rendimiento y cámaras Pro.",
    longDescription:
      "El iPhone 13 Pro Max es el modelo más avanzado de la línea iPhone 13, ofreciendo el máximo rendimiento y las mejores cámaras del mercado. Su pantalla Super Retina XDR de 6.7 pulgadas con ProMotion a 120 Hz proporciona una experiencia visual fluida y envolvente.\n\nEquipado con el chip A15 Bionic, este dispositivo ofrece un rendimiento excepcional para cualquier tarea, desde gaming hasta edición de video profesional. Su sistema de triple cámara Pro de 12 MP con sensor LiDAR permite capturar fotografías y videos cinematográficos impresionantes en cualquier condición de luz.",
    specs: {
      Pantalla: '6.7" Super Retina XDR OLED',
      Resolución: "2778 x 1284 px (458 ppi)",
      "Tasa de refresco": "ProMotion 120 Hz",
      Procesador: "A15 Bionic (5 núcleos GPU)",
      "Cámara trasera": "Triple 12 MP (gran angular, ultra gran angular, teleobjetivo 3x)",
      "Cámara frontal": "12 MP TrueDepth",
      "Resistencia al agua": "IP68",
      "Face ID": "Sí",
      Batería: "Hasta 28 hrs reproducción de video",
      "5G": "Sí",
      Peso: "238 g",
    },
    reviews: [
      {
        author: "Fernando L.",
        rating: 5,
        date: "hace 5 meses",
        text: "Increíble teléfono. Las cámaras son de otro nivel y la batería dura todo el día sin problemas. 100% recomendado.",
      },
      {
        author: "Catalina R.",
        rating: 5,
        date: "hace 1 año",
        text: "Lo mejor que he comprado. Llegó impecable, como nuevo. La pantalla ProMotion se nota mucho.",
      },
      {
        author: "Diego M.",
        rating: 4,
        date: "hace 1 año",
        text: "Gran equipo, el rendimiento es brutal. Solo un poco pesado pero te acostumbras rápido.",
      },
    ],
    chargerPrice: 9990,
  },
  {
    id: "watch-s6",
    title: "Apple Watch Series 6",
    category: "watch",
    categoryLabel: "Apple Watch",
    condition: "seminuevo",
    price: 199990,
    oldPrice: 349990,
    image:
      "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&h=800&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=800&h=800&fit=crop&q=80",
    ],
    colors: [
      { name: "Azul", hex: "#1a3f7a" },
      { name: "Rojo", hex: "#c0392b" },
      { name: "Gris Espacial", hex: "#4a4a4a" },
      { name: "Plata", hex: "#c0c0c0" },
    ],
    capacities: ["40 mm", "44 mm"],
    description: "Oxímetro y siempre activa.",
    longDescription:
      "El Apple Watch Series 6 es el reloj inteligente más completo de Apple, con sensor de oxígeno en sangre, ECG y pantalla Retina siempre activa. Su chip S6 ofrece un rendimiento hasta un 20% más rápido que la generación anterior.\n\nCon funciones avanzadas de salud y fitness, GPS integrado y resistencia al agua de 50 metros, es el compañero perfecto para tu vida diaria y tus entrenamientos.",
    specs: {
      Pantalla: "OLED LTPO Retina siempre activa",
      Chip: "Apple S6 SiP",
      Sensores: "Oxímetro (SpO2), ECG, Altímetro, Acelerómetro, Giroscopio",
      "Resistencia al agua": "50 metros (WR50)",
      GPS: "Integrado",
      Conectividad: "Wi-Fi, Bluetooth 5.0",
      Batería: "Hasta 18 horas",
      Compatibilidad: "iPhone 6s o posterior con iOS 14+",
    },
    reviews: [
      {
        author: "Valentina C.",
        rating: 5,
        date: "hace 7 meses",
        text: "Hermoso reloj, funciona perfecto. El oxímetro es muy útil. Llegó en excelente estado.",
      },
      {
        author: "Tomás G.",
        rating: 4,
        date: "hace 1 año",
        text: "Muy buen reloj. La batería dura un día completo. Ideal para hacer deporte y monitorear la salud.",
      },
    ],
    chargerPrice: 12990,
  },
  {
    id: "ipad-air",
    title: "iPad Air",
    category: "ipad",
    categoryLabel: "iPad",
    condition: "nuevo",
    price: 459990,
    oldPrice: null,
    image:
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&h=800&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=800&h=800&fit=crop&q=80",
    ],
    colors: [
      { name: "Gris Espacial", hex: "#4a4a4a" },
      { name: "Plata", hex: "#c0c0c0" },
      { name: "Oro Rosa", hex: "#e8b4b8" },
      { name: "Verde", hex: "#5a8f5a" },
      { name: "Azul Cielo", hex: "#87ceeb" },
    ],
    capacities: ["64 GB", "256 GB"],
    description: "Chip potente, compatible con Apple Pencil.",
    longDescription:
      "El iPad Air combina un diseño delgado y ligero con un rendimiento potente gracias a su chip de última generación. Su pantalla Liquid Retina de 10.9 pulgadas con True Tone y amplia gama de colores P3 ofrece una experiencia visual increíble.\n\nCompatible con Apple Pencil (2.ª generación) y Magic Keyboard, es la herramienta perfecta para creativos, estudiantes y profesionales. Su cámara frontal con Center Stage mantiene a todos en el encuadre durante las videollamadas.",
    specs: {
      Pantalla: '10.9" Liquid Retina IPS',
      Resolución: "2360 x 1640 px (264 ppi)",
      Chip: "Apple M1",
      "Cámara trasera": "12 MP gran angular",
      "Cámara frontal": "12 MP ultra gran angular con Center Stage",
      "Touch ID": "Sí (botón superior)",
      Conectividad: "Wi-Fi 6, Bluetooth 5.0, USB-C",
      Batería: "Hasta 10 horas de navegación",
      Peso: "461 g",
    },
    reviews: [
      {
        author: "Camila S.",
        rating: 5,
        date: "hace 2 meses",
        text: "Excelente iPad, el chip M1 le da una velocidad increíble. Perfecto para dibujar con Apple Pencil.",
      },
      {
        author: "Andrés B.",
        rating: 5,
        date: "hace 6 meses",
        text: "Lo uso para la universidad y es espectacular. La pantalla es hermosa y la batería dura todo el día.",
      },
    ],
    chargerPrice: null,
  },
  {
    id: "airpods-pro",
    title: "AirPods Pro (2.ª gen.)",
    category: "airpods",
    categoryLabel: "AirPods",
    condition: "nuevo",
    price: 279990,
    oldPrice: null,
    image:
      "https://images.unsplash.com/photo-1606220945770-b2b6ce2aef0e?w=800&h=800&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1606220945770-b2b6ce2aef0e?w=800&h=800&fit=crop&q=80",
      "https://images.unsplash.com/photo-1588423771073-b8903fde1c68?w=800&h=800&fit=crop&q=80",
    ],
    colors: [{ name: "Blanco", hex: "#f5f5f5" }],
    capacities: [],
    description: "Cancelación activa de ruido.",
    longDescription:
      "Los AirPods Pro de 2.ª generación ofrecen cancelación activa de ruido hasta 2 veces más efectiva que la generación anterior, junto con audio adaptivo y modo de transparencia personalizado. El chip H2 de Apple proporciona un audio computacional avanzado.\n\nCon audio espacial personalizado con seguimiento dinámico de la cabeza, cada canción y película se siente envolvente. El estuche de carga MagSafe incluye altavoz integrado y tecnología de localización de precisión con el chip U1.",
    specs: {
      Chip: "Apple H2",
      "Cancelación de ruido": "Activa (ANC) hasta 2x más efectiva",
      "Audio espacial": "Personalizado con seguimiento de cabeza",
      "Modo transparencia": "Adaptivo",
      Conectividad: "Bluetooth 5.3",
      "Resistencia al agua": "IPX4 (audífonos y estuche)",
      "Batería audífonos": "Hasta 6 hrs (ANC activado)",
      "Batería con estuche": "Hasta 30 hrs en total",
      Carga: "MagSafe, Qi, Lightning o USB-C",
    },
    reviews: [
      {
        author: "Sebastián F.",
        rating: 5,
        date: "hace 1 mes",
        text: "La cancelación de ruido es impresionante. Los uso todo el día en la oficina y la calidad de sonido es excelente.",
      },
      {
        author: "Isidora M.",
        rating: 5,
        date: "hace 4 meses",
        text: "Mejores audífonos que he tenido. El audio espacial es una experiencia única. Muy recomendados.",
      },
      {
        author: "Nicolás V.",
        rating: 4,
        date: "hace 8 meses",
        text: "Muy buenos audífonos, sonido increíble. Solo quisiera que la batería durara un poco más con ANC activado.",
      },
    ],
    chargerPrice: null,
  },
];
